apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
 name: omsagent-private-preview-windows
 namespace: kube-system
spec:
 updateStrategy:
  type: RollingUpdate
 template:
  metadata:
   labels:
    dsName: "omsagent-private-preview-windows-ds"
  spec:
   serviceAccountName: omsagent
   containers:
     - name: omsagent-private-preview-windows 
       image: bragi92/fluentbit:03192020
       imagePullPolicy: Always
       resources:
        limits:
         cpu: 1300m
         memory: 500Mi
        requests:
         cpu: 1100m
         memory: 300Mi
       env:       
       - name: CI_WSID
         value: "5e0e87ea-67ac-4779-b6f7-30173b69112a"
       - name: CI_SHARED_KEY
         value: "nqWJ0bSZo7g5p4hr4QLFqMB438csAzPb74HMUHb8086Ne6lrkF/vVUyg/jHDGWHACaUJVX6W/6hxX2Gh+2Uhcg=="
       - name: AKS_RESOURCE_ID
         value: "/subscriptions/692aea0b-2d89-4e7e-ae30-fffe40782ee2/resourceGroups/kaveeshINeedRbac/providers/Microsoft.ContainerService/managedClusters/kaveeshINeedRbac"
       - name: AKS_REGION
         value: "westeurope"
       - name: CONTROLLER_TYPE
         value: "DaemonSet"
       - name: CI_DOMAIN
         value: "opinsights.azure.com"
       - name: CI_CRT_LOCATION
         value: "C://oms.crt"
       - name: CI_KEY_LOCATION
         value: "C://oms.key"
       - name: CI_NODE_IP
         valueFrom:
            fieldRef:
              fieldPath: status.hostIP
       - name: CI_HOSTNAME
         valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
       - name: APPLICATIONINSIGHTS_AUTH
         value: "NzAwZGM5OGYtYTdhZC00NThkLWI5NWMtMjA3ZjM3NmM3YmRi"
       volumeMounts:
        - mountPath: C:\ProgramData\docker\containers
          name: docker-windows-docker-containers
          readOnly: true
        - mountPath: C:\var
          name: docker-windows-kuberenetes-container-logs
          readOnly: true
       livenessProbe:
         exec:
           command:
             - powershell
             - -c 
             - C:\omsagentwindows\livenessProbe.ps1
   nodeSelector:
    beta.kubernetes.io/os: windows    
   # Tolerate a NoSchedule taint on master that ACS Engine sets.
   tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
   volumes:
     - name: docker-windows-kuberenetes-container-logs
       hostPath:
         path: C:\var
     - name: docker-windows-docker-containers
       hostPath:
         path: C:\ProgramData\docker\containers
     